---
version: 2

# Group version updates into a single PR
multi-ecosystem-groups:
  all:
    schedule:
      interval: "monthly"

updates:
  - package-ecosystem: "github-actions"
    multi-ecosystem-group: "all"
    directory: "/"
    patterns: ["*"]
    cooldown:
      default-days: 14

  - package-ecosystem: npm
    multi-ecosystem-group: "all"
    directory: "/"
    patterns: ["*"]
    cooldown:
      default-days: 14
