name: "branch-deploy"
description: "Enabling Branch Deployments through IssueOps with GitHub Actions"
author: "Grant Birkinbine"
branding:
  icon: 'git-branch'
  color: 'green'
inputs:
  github_token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: true
  step_context:
    description: The step context from the GitHub Action
    required: true
  environment:
    description: 'The name of the environment to deploy to. Example, "production"'
    required: false
    default: "production"
  reaction:
    description: 'If set, the specified emoji "reaction" is put on the comment to indicate that the trigger was detected. For example, "rocket" or "eyes"'
    required: false
    default: "eyes"
  trigger:
    description: 'The string to look for in comments as an IssueOps trigger. Example: ".deploy"'
    required: false
    default: ".deploy"
  noop_trigger:
    description: 'The string to look for in comments as an IssueOps noop trigger. Example: "noop"'
    required: false
    default: "noop"
  stable_branch:
    description: 'The name of a stable branch to deploy to (rollbacks). Example: "main"'
    required: false
    default: "main"
  prefix_only:
    description: 'If "false", the trigger can match anywhere in the comment'
    required: false
    default: "true"
outputs:
  triggered:
    description: 'The string "true" if the trigger was found, otherwise the string "false"'
  comment_body:
    description: The comment body
  noop:
    description: 'The string "true" if the noop trigger was found, otherwise the string "false"'
  ref:
    description: The branch to use with deployment
  comment_id:
    description: The comment id which triggered this deployment
runs:
  using: "node16"
  main: "dist/index.js"
  post: "dist/index.js"
