name: "test"

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: read
  deployments: write

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v3.0.2
  
      # Start the branch deployment
      - uses: ./
        id: branch-deploy-start
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Do some fake deployment logic here
      - name: fake deploy
        id: deployment
        run: echo "fake deploy"

      # Post the deployments results back to the PR as a comment and complete the deployment
      - uses: ./
        with:
          post_deploy: true
          data: ${{steps.branch-deploy-start.outputs.data}}
          deployment_status: ${{ steps.deployment.outcome }}
          deployment_message: ${{ steps.deployment.outcome }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
