name: "test"

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  deployments: write
  contents: read

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v3.0.2
  
      # Start the branch deployment
      - uses: ./
        with:
          step_context: ${{ toJSON(steps) }}

      # Do some fake deployment logic here
      - name: fake deploy
        id: deployment
        run: echo "fake deploy"
